### ISSUE TITLE
Rewrite in shell

### ISSUE THREAD

**Issue by apprehensions** [vinegar-dev/vinegar#3]
+ Smaller
+ Easier to debug
+ Easier to write in
+ Easier to implement various to various features
+ Easier in everything.

**Comment by apprehensions** [comment]
Additionally, it fits Vinegar's goal, which is to **be a bloody wrapper for applications**. It is not complex and is meant to be transparent and simple as appose to Grapejuice.

**Comment by Thelolguy1** [comment]
We've been over this already. Go has better distro support by packaging everything, rather than making assumptions of what programs people have installed with shell. Its readability is really quite good already, considering it just follows the standard structure of any other language. Additionally, we already have the majority of the features programmed in; it's going to be a HUGE hassle to rewrite everything.

**Comment by apprehensions** [comment]
> Go has better distro support by packaging everything

Packaging what?

> rather than making assumptions of what programs people have installed with shell.

Do people not have the standard core utilities? is POSIX a joke to you?

> is really quite good already, considering it just follows the standard structure of any other language.

Took me a while to even get started with how the syntax is structured, coming from C: `var string[]` -> `[]string var`

> we already have the majority of the features programmed in; it's going to be a HUGE hassle to rewrite everything.

I'd be more than willing to rewrite.
